PREFIX mov: <https://ekgf.org/ontology/movies/>
PREFIX movdata: <https://ekgf.org/data/movies/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?movuri 
    mov:hasIMDBscore  ?score ;
    mov:hasIMDBraters ?votes .    
}
WHERE {
  BIND ( URI(CONCAT("https://ekgf.org/data/movies/movie_", ?tconst)) AS ?movuri)
  BIND (xsd:decimal(?averageRating) as ?score )
  BIND (xsd:integer(?numVotes) as ?votes )
} 
