PREFIX mov: <https://ekgf.org/ontology/movies/>
PREFIX movdata: <https://ekgf.org/data/movies/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?movuri a mov:Movie ;
    rdfs:label ?primaryTitle ;
    mov:hasReleaseDate ?year ;
    mov:hasRuntime ?mins .     
}
WHERE {
  BIND ( URI(CONCAT("https://ekgf.org/data/movies/movie_", ?tconst)) AS ?movuri)
  BIND ( xsd:integer(?startYear) as ?year )
  BIND ( xsd:integer(?runtimeMinutes) as ?mins )
} 

CONSTRUCT {
  ?movuri 
    mov:hasGenre ?genuri .     
}
WHERE {
  BIND ( URI(CONCAT("https://ekgf.org/data/movies/movie_", ?tconst)) AS ?movuri)  
  ?genre apf:strSplit (?genres ",")
  FILTER (STRLEN(?genre) > 2) .
  BIND ( URI(CONCAT("https://ekgf.org/data/movies/genre_", ?genre)) AS ?genuri)
} 

